ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"

urlpatterns = [
    path('addtocart/<p>',views.add_to_cart,name='addtocart'),
    path('cartview',views.cartview,name='cartview'),
    path('cart_remove/<p>',views.cart_remove,name='cart_remove'),
    path('full_remove/<p>',views.full_remove,name='full_remove'),
    path('orderform',views.orderform,name='orderform'),
    path('orderview',views.orderview,name='orderview'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart',include('cart.urls')),
    path('search',include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
    path('search',views.search,name='search'),
   
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('',views.allcategories,name='allcat'),
    path('allproducts/<p>',views.allproducts,name='allproducts'),
    path('details/<p>',views.details,name='details'),
    path("register",views.register,name='register'),
    path("login",views.user_login,name='login'),
    path("logout",views.user_logout,name="logout"),
]

ecommerce/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import product


# Create your models here.
class cart(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name
    
    def subtotal(self):
        return self.quantity*self.product.price
    
class Order(models.Model):
    product = models.ForeignKey(product,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.CharField(max_length=30)
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    date_ordered=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum
        
    
    

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=200)
    dese=models.TextField()
    image=models.ImageField(upload_to='shop/categories',blank=True,null=True)
    def __str__(self):
        return self.name
class product(models.Model):
    name=models.CharField(max_length=200) 
    dese=models.TextField()  
    image=models.ImageField(upload_to='shop/categories',blank=True,null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(category,on_delete=models.CASCADE)#one to many
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import product
from cart.models import cart
from cart.models import Account,Order

# Create your views here.
def cartview(request):
    total=0
    u=request.user
    try:
        c=cart.objects.filter(user=u)

        for i in c:
            total+=i.quantity*i.product.price
    except:
        pass
      
    return render(request,'cart.html',{'c':c,'total':total})

@login_required
def add_to_cart(request,p):
    pro=product.objects.get(name=p)
    u=request.user
    try:
        c=cart.objects.get(user=u,product=pro)
        if(c.quantity<c.product.stock):
            c.quantity+=1
        c.save()
    except:    
        c=cart.objects.create(product=pro,user=u,quantity=1)
        c.save()
        
        
    return redirect('cart:cartview')

def cart_remove(request,p):
    pro=product.objects.get(name=p)
    user=request.user
    try:
        c=cart.objects.get(user=user,product=pro)
        if c.quantity>1:
            c.quantity-=1
            c.save()
        else:
            c.delete()      
            
    except:
        pass
    return redirect('cart:cartview')


def full_remove(request,p):
    pro=product.objects.get(name=p)
    user=request.user
    try:
        c=cart.objects.get(user=user,product=pro)
        
        c.delete()      
            
    except:
        pass
    return redirect('cart:cartview')

def orderform(request):
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        u=request.user
        c=cart.objects.filter(user=u)
    
    #total amount calculate
        total=0
        for i in c:
            total+=i.quantity*i.product.price
    
        ac=Account.objects.get(acctnum=n)#amount minus in database code  
        if(ac.amount>=total):
            ac.amount=ac.amount-total
            ac.save()
            
            
            for i in c:  #creates record in Order table for each object in cart table for the current user
                o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                o.save()
                i.product.stock=i.product.stock-i.quantity
                i.product.save()
            c.delete()  #clears the cart items for the current user
            msg="Order placed Successfully"
            return render(request,'orderdetails.html',{'m':msg})
        else:
            msg="Insufficient Amount in User Account.You cannot place order."  
            return render(request,'orderdetails.html',{'m':msg})
    return render(request,'orderform.html')
        
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import product
from django.db.models import Q

def search(request):
    q = ""
    p=None
    if(request.method=="POST"):
        q = request.POST['q']
        if q:
            p=product.objects.filter(Q(name__icontains=q)|Q(id__icontains=q))
    return render(request, 'search.html', {'p':p,'query':q})

ecommerce/shop/views.py
from django.shortcuts import render,redirect
from shop.models import category,product
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
# Create your views here.
def allcategories(request):
    a=category.objects.all()
    return render(request,'category.html',{'allcat':a})


def allproducts(request,p):
    c=category.objects.get(name=p)
    pro=product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':pro})

def details(request,p):
    pro=product.objects.get(name=p)
    return render(request,'detail.html',{'p':pro})


def register(request):
    if(request.method=="POST"):
        u=request.POST["u"]
        p=request.POST["p"]
        cp=request.POST["cp"]
        e=request.POST["e"]
       
        if(p==cp):
            u=User.objects.create_user(username=u,password=p,email=e)
            return redirect("shop:allcat")
        else:
            return redirect("password not matching")
    return render(request,'regi.html')

def user_login(request):
    if(request.method=="POST"):
        name=request.POST['u']
        pass1=request.POST['p']
        user=authenticate(username=name,password=pass1)
        if user:
            login(request,user)
            return redirect('shop:allcat')
        else:
            messages.error(request,"Invalid credentails")
    return render(request,'login.html')

def user_logout(request):
    logout(request)  
    return redirect('shop:allcat')

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" integrity="sha384-4LISF5TTJX/fLmGSxO53rV4miRxdg84mZsxmO8Rx5jGtp/LbrixFETvWa5a6sESd" crossorigin="anonymous"></head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css" integrity="sha384-BY+fdrpOd3gfeRvTSMT+VUZmA728cfF9Z2G42xpaRkUGu2i3DyzpTURDo5A6CaLK" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    <body>
<header>
<center><img src="{% static 'images/lo.png' %}" style="height="150px" width="150px" class="mb-2""></center>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">My Shop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              All Categories
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
              <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name%}">{{i.name}}</a></li>
              {% endfor %}
              
            </ul>
          </li>

          {% if user.is_authenticated %}
          {% if user.is_superuser == False %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i>&nbsp;&nbsp;<sub>{{count}}<sub></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
          </li>
          {% endif %}

        <li class="nav-item">
        <li><a class="dropdown-item" href="{% url 'shop:logout' %}">Logout</a></li>
        </li>
        {% else %}

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">Login</a>
          </li>
      {% endif %}
        </ul>
        <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
          <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>  
{% block content %}
{% endblock %} 
     
<footer>

<div class="mt-5 footer">
  <center>
  <p class="mt-2"><i class="fa-regular fa-copyright"></i>Myshop pvt ltd.All Rights Reserved</p>
</div>
</center> 
</footer>


</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if not c %}
<div class="container mt-3">
<h3 class="text-center">Cart is Empty</h3>
<h5 class="text-center text-success"><a href="{% url 'shop:allcat' %}">Continue Shopping</a></h5>
</div>


{% else %}
<div class="container-fluid m-3">
<div class="row">
    <h4 class="text-center">Shopping Cart</h4>

    <div class="col-sm-6">
        <table class="table table-bordered">
        <tr>
            <th colspan="5" class="text-center" >Cart Items</th>
        </tr>
        {% for i in c %}
        <tr>
            <td><img src="{{i.product.image.url}}" height="200px" width="200px"></td>
            <td><b>{{i.product.name}}</b></td>
            <td><b>Product id:{{i.product.id}}</b><br>
            <b>Unit Price:{{i.product.price}}</b><br>
            <b>Quantity:{{i.quantity}}*{{i.product.price}}</b></td>
        
            <td><b>SubTotal:{{i.subtotal}}</b></td>
            <td>
            {% if i.quantity < i.product.stock %}
                <a href="{% url 'cart:addtocart' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-regular fa-plus"></i></a>
                <a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-sharp fa-solid fa-minus"></i></a>
                <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black;font-size:20px;"  class="fa-sharp fa-solid fa-trash"></i></a></td>
            {% else %}
                <a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-sharp fa-solid fa-minus"></i></a>
                <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black;font-size:20px;"  class="fa-sharp fa-solid fa-trash"></i></a></td>
            </tr>
            {% endif %}
    {% endfor %}
    </table>
    </div>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <div class="col-sm-4">
        <table class="table table-bordered">
        <tr><th colspan="4" class="text-center">Check Out</th></tr>
    <tr><td class="text-center"><b>Total: <span class="text-danger">{{total}}</span></b></td></tr>
    </table>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'cart:orderform' %}" class="btn btn-danger text-dark"><b>Place Order</b></a>
    <a href="{% url 'shop:allcat' %}" class="btn btn-danger text-dark"><b>Continue Shopping</b></a>
    </div>
    </div>

</div>
</div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'images/banner.jpg' %}" height="300px;" width="100%"%>
</div>
    <div class="container-fluid mt-2" style="margin-bottom:100px;">
        <h3 class="text-center fw-3">Our collections</h3>
    <p style="line-height=1.8;text-align:justify;">Ecommerce is a method of buying and selling goods and services online. The definition of ecommerce business can also include tactics like affiliate marketing. You can use ecommerce channels such as your own website, an established selling website like Amazon, or social media to drive online sales.</p>
    </div>

    <div class="row">
      {% for i in allcat %}
        <div class="col-md-4" style="margin-bottom:100px"><div class="card ms-5 me-5" style="width:350px;height:460px">
            <center>
              <img style="height:220px; width:340px;" src="{{i.image.url}}" class="card-img-top mt-1" alt="">
            </center>
            <div class="card-body">
              <center>
              <h5 class="card-title" style="...">{{i.name}}</h5>
              <p style=".." class="card-text">{{i.dese}}</p>
            
              <a href="{% url 'shop:allproducts' i.name %}" class="btn btn-primary"style="font-weight:bold">SHOP</a>
              </center>
            </div>
          </div></div>

          {% endfor %}
          
                    </div>
                  </div>

{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container mt-5" style="...">
    <div class="row">
        <div class="col-sm-4"><img src="{{p.image.url}}" hright="370px" width="370px"></div> 
            <div class="col-sm-5">
            <h4>{{p.name}}</h4>
            <h5 class="mt-4">{{p.price}}</h5>
            <p class="mt-2" style="..">{{p.desc}}</p>
            {% if user.is_superuser == False %}

            {% if p.stock <= 0 %}
            <h4> Out Of stock</h4>
            {% else %}
        <h4><a href="{% url 'cart:addtocart' p.name %}" class="btn btn-secondary mt-4">Add To Cart</a></h4>
                {% endif %}

                {% else %}
                {% if p.stock <= 0 %}
                <h4> Out Of stock</h4>
                <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary mt-4">add stock</a></h4>
                {% else %}
                <h4>PRODUCT IN STOCK<h4>
                    <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary mt-4">add stock</a></h4>
                {% endif %}
{% endif %}
    
    </div>
    </div>
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>

{%  extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3>LOGIN</h3>
<form method="POST">
  {% csrf_token %}
  
  <div class="mb-3" style="background-color:pink; width:50%">
    <label class="form-label">USERNAME</label>
    <input type="username" class="form-control" placeholder="ENTER THE USERNAME" name="u">
  </div>

  <div class="mb-3"style="background-color:pink;width:50%">
    <label class="form-label">PASSWORD</label>
    
    <input type="password" class="form-control" placeholder="ENTER THE PASSWORD" name="p">
  </div>

  <div class="mb-3"style="background-color:pink;width:50%">
    <input type="submit" class="form-control">
    </div>
</center>

    <center><strong><span class="psw">Forgot <a href="#">password?</a></span></strong></center>
</form>
{% if messages %}
{% for i in messages %}
<ul>
    <li>{{i}}</li>
</ul>    

{% endfor %}    
{% endif %}    

{% endblock %}

ecommerce/templates/orderdetails.html
{% extends 'base.html' %}
{% load  static %}
{% block content %}
<div class="container-fluid mt-5" style="..">
    <center>
        <h3 class="text-center text-scondary">{{m}}</h3>
        <h5 class="text-centre text-success">Thanku You</h5>
        <h6><a href="{%url 'shop:allcat' %}">Continue Shopping</a></h6>
        <div class="col-sm-6">
            <table class="table table-bordered">
            <tr>
                <th colspan="5" class="text-center" >Cart Items</th>
            </tr>
            {% for i in c %}
            <tr>
                <td><img src="{{i.product.image.url}}" height="200px" width="200px"></td>
                <td><b>{{i.product.name}}</b></td>
                <td><b>Product id:{{i.product.id}}</b><br>
                <b>Unit Price:{{i.product.price}}</b><br>
                <b>Quantity:{{i.quantity}}*{{i.product.price}}</b></td>
            
                <td><b>SubTotal:{{i.subtotal}}</b></td>
                <td>
                {% if i.quantity < i.product.stock %}
                    <a href="{% url 'cart:addtocart' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-regular fa-plus"></i></a>
                    <a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-sharp fa-solid fa-minus"></i></a>
                    <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black;font-size:20px;"  class="fa-sharp fa-solid fa-trash"></i></a></td>
                {% else %}
                    <a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-sharp fa-solid fa-minus"></i></a>
                    <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black;font-size:20px;"  class="fa-sharp fa-solid fa-trash"></i></a></td>
                </tr>
                {% endif %}
    </center>
{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      {% block content %}
      <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <div class="mb-3">
                <label class="form-label">ADDRESS</label>
                <textarea class="form-control"  name="a"></textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">PHONE</label>
                <input type="text" class="form-control" placeholder="ENTER THE PHONE NUMBER" name="p">
            </div>
            <div class="mb-3"></div>
                <label class="form-label">Account Number</label>
                <input type="text" class="form-control" placeholder="ENTER THE ACCOUNT NUMBER" name="n">
            </div>
            
         
          <div class="mb-3">
                    <input type="submit" class="form-control">
          </div>
        </form>
    {% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h4 class="mt=3"><b>Customer Name:</b>{{user.username}}</h4>
<div class="container-fluid" style="width:100%;height:300px;">
<div class="row">
    <h4 class="text-center"> Order Views </h4>

    <div class="col-sm-6"style="mt-5">
        <table class="table table-bordered">
            {% for i in o %}
        <tr>
            <td>
                <img style=".."  src="{{i.product.image.url}}">
            </td>
            
            <td>
            <h5 style="font-weight:bold">Order Address:{{i.address}}</h5>
            <h5 style="font-weight:bold">Contact Number:{{i.phone}}</h5>
            <h5 style="font-weight:bold">Product Price:{{i.product.price}}</h5>
            <h5 style="font-weight:bold">Oredered On:{{i.no_of_items}}</h5>
            <h5 style="font-weight:bold">Order Date:{{i.date_ordered}}</h5>
             <h5 style="font-weight:bold">Devlivery Status:{{i.delivery_status}}</h5>

            <td>
            </tr>  

        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-4" style="margin-botton:100px:">  
 <center><img src="{{c.image.url}}" width=50% height="450px"></center>
</div>

<div class="container-fluid mt-4" style="margin-botton:50px;">
    <h3 class="text-center fw-bold">{{c.name}}</h3>
    <p style="line-height:1.8; text-a;ign:justify;">{{c.desc}}</p>
</div>
<div class="container-fluid mt-2" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width:30rem;">
                <img src="{{i.image.url}}" class="card-img-top" alt=".." height="250px" width="100%;">
                <div class="card-body">
                    <h4 class="card-title text-center">{{i.name}}</h4>
                    <h5 class="text-center">{{i.price}}</h5>
                    <a href="{% url 'shop:details' i.name %}" class="btn btn-primary" style="position:relative;left:38%">Details</a>

                </div>
            </div>
        </div>{% endfor %}

        {% endblock %}

ecommerce/templates/regi.html
<!DOCTYPE html>
{% extends 'base.html' %}
    {% load static %}
    {% block content %}
    <h3>REGISTER HERE</h3>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3" style="background-color:pink;">
          <label class="form-label">USERNAME</label>
          <input type="text" class="form-control" placeholder="ENTER THE USERNAME" name="u">
                 <div class="mb-3"style="background-color:pink;">
          <label class="form-label">PASSWORD</label>
          <input type="password" class="form-control" placeholder="ENTER THE PASSWORD" name="p">
        </div>
        <div class="mb-3"style="background-color:pink;">
            <label class="form-label">CONFIRM PASSWORD</label>
            <input type="password" class="form-control" placeholder="CONFIRM PASSWORD" name="cp">
          </div>
          <div class="mb-3"style="background-color:pink;">
            <label class="form-label">EMAIL</label>
            <input type="email" class="form-control" placeholder="ENTER THE EMAIL" name="e">
          </div>
          <div class="mb-3"style="background-color:pink;">
            <label class="form-label">phone</label>
            <input type="phon" class="form-control" placeholder="ENTER THE phone number" name="n">
          </div>

          <div class="mb-3"style="background-color:pink;">
            <label class="form-label">address</label>
            <input type="text" class="form-control" placeholder="ENTER THE address" name="a">
          </div>

          <div class="mb-3"style="background-color:pink;">
                    <input type="submit" class="form-control">
          </div>
          <div class="mb-3">
  <input type="login" class="form-control">
</div>
        </form>
    {% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<center>
    <div class="text-center">You have searched for <span class="text-danger fw-bolder"><i>{{query}}</i></span></div></center>
    <div class="container-fluid mt-4" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
    <div class="col-sm-4">
        <div class="card" style="width: 30 rem;">
    <img src="{{i.image.url}}" class="card-img-top" alt="..." height="250px" width="100%">
    <div class="card-body">
        <h3 class="text-title text-center">{{i.name}}</h3>
            <h4 class="text-center">{{i.price}}</h4>
        <a href="{ url 'shop:p' i.name}" class="btn btn-primary" style="postion:relative;left:30%">Details</a>
    </div>
</div>
</div>
{% empty %}
        <h4 class="text-center text-danger">No Search Results Found</h4>
        {% endfor %}
</div>
</div>


{% endblock %}